# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_project_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='complete',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
