# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 09:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20160716_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='project',
            name='modified',
        ),
    ]
