# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20160716_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deleted',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='modified',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
