# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 14:57
from __future__ import unicode_literals

from django.db import migrations, models
from datetime import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20160716_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='auto_hide_left_bar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='backup_to_dropbox',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created',
            field=models.DateTimeField(auto_now=True, default=datetime.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='font',
            field=models.PositiveIntegerField(choices=[(0, 'default')], default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='monthly_item_quota',
            field=models.PositiveIntegerField(default=5000),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_completed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_keyboard_shortcuts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='theme',
            field=models.PositiveIntegerField(choices=[(0, 'default')], default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='unsubscribe_from_summary_emails',
            field=models.BooleanField(default=True),
        ),
    ]
