# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_auto_20160717_1457'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['priority']},
        ),
        migrations.AlterField(
            model_name='project',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
