# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 21:12
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_auto_20160808_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='saved_views_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
