# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-10 22:25
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_userprofile_saved_views_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='saved_views_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='show_keyboard_shortcuts',
            field=models.BooleanField(default=False),
        ),
    ]
