# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-31 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_auto_20160831_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
