# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-31 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_auto_20160831_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
